version: '3.2'
services:
  php-environment:
    container_name: php-apache
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
  testing-environment:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      - php-environment
    volumes:
      - ./tests:/var/www/html/tests
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "9906:3306"